### ISSUE TITLE
Unknown custom element: <stripe-elements> - did you register the component correctly?

### ISSUE THREAD

**Issue by zmaglica** [vue-stripe/vue-stripe#155] opened 2020-12-23 07:36 UTC
**Describe the bug**
I am getting the following error:

` Unknown custom element: <stripe-elements> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**To Reproduce**
Used following code that is similar like on in the documentation to create a payment form

```
<template>
    <div id="payment-method" class="row">
        <div class="col-9">
            <div>
                <h2>Details</h2>
                <p class="text-muted">Payment form</p>
            </div>
            <template>
                <div>
                    <stripe-elements
                        ref="elementsRef"
                        :pk="publishableKey"
                        :amount="amount"
                        locale="de"
                        @token="tokenCreated"
                        @loading="loading = $event"
                    >
                    </stripe-elements>
                    <button @click="submit">Pay ${{amount / 100}}</button>
                </div>
            </template>
        </div>

        <div class="col-3">
            <payment-steps-ui :seller="$parent.seller"/>
        </div>
    </div>
</template>

<script>
import {StripeElements} from 'vue-stripe-checkout'
import PaymentStepsUi from '../partials/PaymentStepsUi';
export default {
    components: {PaymentStepsUi, StripeElements},
    data() {
        return {
            offer: Object,
            loading: false,
            amount: 1000,
            publishableKey: this.$parent.publishableKey,
            token: null,
            charge: null
        }
    },
    mounted() {
        this.offer = this.$parent.offer;
        this.seller = this.$parent.seller;
    },
    methods: {
        submit () {
            this.$refs.elementsRef.submit();
        },
        tokenCreated (token) {
            this.token = token;
            // for additional charge objects go to https://stripe.com/docs/api/charges/object
            this.charge = {
                source: token.id,
                amount: this.amount, // the amount you want to charge the customer in cents. $100 is 1000 (it is strongly recommended you use a product id and quantity and get calculate this on the backend to avoid people manipulating the cost)
                description: this.description // optional description that will show up on stripe when looking at payments
            }
            this.sendTokenToServer(this.charge);
        },
        sendTokenToServer (charge) {
            // Send to charge to your backend server to be processed
            // Documentation here: https://stripe.com/docs/api/charges/create

        },
        next() {
            this.$parent.component = "meeting-select";
        }
    },

}
</script>
```

**Expected behavior**
It shouldn't throw an error in the console.

**Comment by jeremyd125** [comment] 2020-12-24 18:34
I'm getting the same!

**Comment by jofftiquez** [comment] 2020-12-25 06:59
Hello, @zmaglica thanks for this. Based on how it was exported [here](https://github.com/jofftiquez/vue-stripe-checkout/blob/4bfe865b555020c862f22a600c581ab1a74814ee/src/index.js#L4), it should work as intended. I double-checked my own implementation on my application and there seems to be no problem. Here's what you can do for now:

1. Look for other potential external errors that might block the rendering of the scripts related to this plugin
2. Kindly provide more details of your implementation, are you using Nuxt.js, etc.
3. If you could send a reproduction link, that would be a great help.

Thank you.

**Comment by LilPidgey** [comment] 2020-12-29 00:43
Are you using Vue 3? I was getting this error earlier until I had realized this package does not support Vue 3.

**Comment by jofftiquez** [comment] 2020-12-29 06:45
Hello @LilPidgey no, not yet. Supporting v3 is in my plans tho. Just don't have a date yet, but probably first quarter of 2021. Thank you.

**Comment by franciscoramoso** [comment] 2021-01-04 01:01
Same here :(

**Comment by jofftiquez** [comment] 2021-01-04 09:21
Guys if you're using this for vue 3 I apologize but this doesn't support it yet. Please bear with me, I will make this happen soon. I'm just a little busy but this is something that I am also looking forward to. Thank you for your patience.

**Comment by kvaes** [comment] 2021-01-08 19:43
Same, version 2.6.12

**Comment by victorcorbat** [comment] 2021-01-10 00:16
Hi, I'm using version 2.6.12 aswell and it gives me the same error: "Unknown custom element: <StripeElements> - did you register the component correctly?"

Does anyone know how to fix it? Thanks in advance!!

**Comment by jofftiquez** [comment] 2021-01-10 03:57
Hello @kvaes and @victorcorbat, may I see how you implemented it? Thanks.

**Comment by victorcorbat** [comment] 2021-01-10 11:37
Thank you jofftiquez! I was importing vue-stripe-checkout globally at the main.js. Now i'm importing it directly at the component like in the following code, and i'm getting the following error: "You are using the runtime-only build of Vue where the template compiler is not available." I tried to modify the config files (vue config and webpack.config) but it still doesn't work. Any help will be very appreciated!!

<template>
  <stripe-checkout
    ref="checkoutRef"
    :pk="publishableKey"
    :items="items"
    :successUrl="successUrl"
    :cancelUrl="cancelUrl"
  >
    <template slot="checkout-button">
      <button @click="checkout">Shut up and take my money!</button>
    </template>
  </stripe-checkout>
</template>

<script>

import { StripeCheckout } from 'vue-stripe-checkout';

export default {
  components: {
    StripeCheckout
  },
  data: () => ({
    loading: false,
    publishableKey: 'pk_test_51I3lJrCujnizGY8n6EpzfjOjSrq8f3965zG4s81fVmYgwNrslX3TbDOoF4ieZdMKrQGTRyugFPnOARa0tDKIsnbQ00bh1eREiN',
    items: [
      {
        sku: 'sku_FdQKocNoVzznpJ', 
        quantity: 1
      }
    ],
    successUrl: 'your-success-url',
    cancelUrl: 'your-cancel-url',
  }),
  methods: {
    checkout () {
      this.$refs.checkoutRef.redirectToCheckout();
    }
  }
}
</script>

**Comment by jofftiquez** [comment] 2021-01-10 12:16
Hello @victorcorbat I will look into this. Thanks.

**Comment by dappiu** [comment] 2021-01-11 11:51
@jofftiquez I am experiencing the same issue of @victorcorbat with Nuxt.
The last version that works for me is 3.5.13. Using 3.5.14-beta.0 or 4.0.2 produces this error when the component is shown on page:

```[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.```

**Comment by jofftiquez** [comment] 2021-01-11 12:41
@dappiu I was able to reproduce this. I will look into it asap. Thank you for reporting.

**Comment by jofftiquez** [comment] 2021-01-12 09:05
Hello would mind trying this version? `@vue-stripe/vue-stripe@4.0.3`. Thanks.

**Comment by dappiu** [comment] 2021-01-12 17:30
@jofftiquez I'm afraid that something's not right, but I will look further tomorrow.
For now I just had a quick test changing the import in the plugin file (I'm using Nuxt) but the component didn't render anything where the old version correctly renders the button inside the slot. I will do a quick test tomorrow using your repo with Nuxt example and will see.
Thank you.

**Comment by jofftiquez** [comment] 2021-01-13 00:20
Thanks @dappiu please let me know if anything comes up. I'm kind of in a slump right now. I can't reproduce some reported behavior. I really wanna solve this so I can continue with creating more sample docs. Thank you again.

**Comment by nelsw** [comment] 2021-01-17 23:29
I was able to solve this issue by aliasing the component.

Try naming the component `VueStripeCheckout` and use the following import statement `import {StripeCheckout as VueStripeCheckout} from "@vue-stripe/vue-stripe"`

**Comment by jofftiquez** [comment] 2021-01-17 23:56
@nelsw really? Hmm that's weird. Thanks for the info.

**Comment by napter** [comment] 2021-02-03 05:54
@jofftiquez  I just started getting this error and the stripe elements won't render anymore on version 3.5.15. Version 3.1.13 did not throw the error. Vue is vue@2.6.11.

"You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build"

**Comment by jofftiquez** [comment] 2021-02-03 06:17
@napter have you tried the latest version yet? The old `vue-stripe-checkout` is now deprecated. Please see https://vuestripe.com

**Comment by napter** [comment] 2021-02-03 06:20
> @napter have you tried the latest version yet? The old `vue-stripe-checkout` is now deprecated. Please see https://vuestripe.com

Yes. I tried @vue-stripe/vue-stripe - same error - but the issue does not occur after downgrading to 3.5.13 .

**Comment by napter** [comment] 2021-02-03 06:20
> @napter have you tried the latest version yet? The old `vue-stripe-checkout` is now deprecated. Please see https://vuestripe.com



> @napter have you tried the latest version yet? The old `vue-stripe-checkout` is now deprecated. Please see https://vuestripe.com

@jofftiquez  Yes. I tried @vue-stripe/vue-stripe, but the error still occurs. The issue does not occur after downgrading to 3.5.13 .

**Comment by jofftiquez** [comment] 2021-02-03 06:22
May I see your implementation? Or a reproduction link perhaps? Thanks. 

@napter

**Comment by napter** [comment] 2021-02-03 07:30
@jofftiquez  here is the code of the vue file: https://pastebin.pl/view/9398834e

Relevant bits:

`import { StripeCheckout } from "vue-stripe-checkout";
`
`                <stripe-checkout ref="sessionRef" :pk="publishableKey" :session-id="sessionId">
                  <template slot="checkout-button">

                  </template>
                </stripe-checkout>
`
`  components: {
    StripeCheckout,
    // StripeElements,
  },
`

**Comment by dappiu** [comment] 2021-02-03 08:56
I can confirm versions above 3.5.13 do not render anything when the component is used as instructed.

**Comment by jofftiquez** [comment] 2021-02-03 10:21
Hello @napter @dappiu I tried to recreate the reported errors but I really can't find anything. If you guys can send me a reproduction link using the latest version that would be the fastest way for me to work on this. Thanks.

**Comment by dappiu** [comment] 2021-02-04 13:59
Well, as I said in a previous comment, you could see that very easily using your [vue-stripe-checkout-nuxt-demo](https://github.com/vue-stripe/vue-stripe-checkout-nuxt-demo) repository by just replacing the old package with the new, and replacing the import in the plugin file.

I moved forward and I did that for you right here: https://github.com/dappiu/vue-stripe-checkout-nuxt-demo so you just have to 

1. Clone my fork
2. Launch `yarn install`
3. Launch `SITE_NAME=localhost:3000 STRIPE_PK=<your_stripe_pk> yarn dev` (or put those variables in .env, same thing)
4. Navigate to localhost:3000
5. You will see that the button is missing

You can verify that I just swapped the dependency and I updated the import in `plugins/vue-stripe-checkout.js`. Changeset here: https://github.com/dappiu/vue-stripe-checkout-nuxt-demo/commit/8337411ea515fbbb043c26d87f43e5801223a0a7

Then, I also set up another branch called vsc_3_5_13 where I brought back the `vue-stripe-checkout@3.5.13` so you can do:
1. Swap branch: `git checkout vsc_3_5_13`
2. Launch `yarn install`
3. Launch `SITE_NAME=localhost:3000 STRIPE_PK=<your_stripe_pk> yarn dev`
4. 4. Navigate to localhost:3000
5. You will see that the button **is now rendered** and correctly working.

Finally, I also set up a branch `vsc_3_5_15` using vue-stripe-checkout@3.5.15, that you will see that shares the same problems of `@vue-stripe/vue-stripe`

**Comment by jofftiquez** [comment] 2021-02-04 15:55
@dappiu thanks for the instructions. I got confused my bad. I will check this as soon as I get back to the project. Thanks.

The current docs website is also made with Nuxt and it's working. Maybe you can also check it, it might help. Thanks.

**Comment by dappiu** [comment] 2021-02-04 16:27
Looking at the `vuestripe.com` repo, the problem starts getting clear: 

Up until version 3.5.13, you could use the default slot of your components to render things, as in:
```
<stripe-checkout>
  <button>Pay</button>
</stripe-checkout>
```

But now it seems that the content inside the component's slot gets discarded, and in fact you place the buttons as siblings of <stripe-checkout> component and not inside its default slot, as in:
```
<stripe-checkout></stripe-checkout>
<button>Pay</button>
```

**Comment by jofftiquez** [comment] 2021-02-04 17:28
I understand. I decided to remove the slot for the button to make it more dynamic in terms of the checkout component placing. This is my fault for the lack of changelogs. It would be best to use the latest version moving forward. I will update the necessary docs. Perhaps I could write some FAQs, caveats, or the likes. 

Thank you for this @dappiu very helpful input.

**Comment by jofftiquez** [comment] 2021-04-08 00:47
This should be not a problem anymore in the latest version. Kindly check. Closing this for now, please open a new issue if you find anything odd again. Thank you! Stay safe everyone.

**Closed by jofftiquez** 2021-04-08 00:47 UTC
