### ISSUE TITLE
Stripe Client Reference ID "ignored"

### ISSUE THREAD

**Issue by hcphoon01** [vue-stripe/vue-stripe#230] opened 2021-10-13 18:21 UTC
**Describe the bug**
I am setting the `clientReferenceId` field in the stripe checkout component to a valid customer id, but each time I hit the subscribe button on stripe's website after filling in payment details, it creates a new customer and doesn't use the customer id.

**To Reproduce**
1. Go to the stripe dashboard
2. Create Customer
3. Copy Customer ID and paste into `clientReferenceId` field

**Expected behavior**
I expect Stripe not to create a new customer and to link the purchase to the customer with the given ID

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 94

**Comment by jofftiquez** [comment] 2022-01-25 18:08
Hello upon checking the `clientReferenceId` prop is being used just fine by Vue Stripe. You may check here:

Prop:
https://github.com/vue-stripe/vue-stripe/blob/ab6afa7da3529b7d4bc3bb86d849e91a02a0d184/src/checkout/props.js#L41

Options setup:
https://github.com/vue-stripe/vue-stripe/blob/master/src/checkout/index.js#L47

Options usage:
https://github.com/vue-stripe/vue-stripe/blob/master/src/checkout/index.js#L58

I am not really sure what's happening but maybe the problem is within Stripe SDK itself. I have no more control over what happens to the props after passing them to `stripe.redirectToCheckout`. Closing this for now. Thanks.

**Closed by jofftiquez** 2022-01-25 18:08 UTC

**Comment by juloxrox** [comment] 2022-01-29 00:57
@hcphoon01 You can solve this by generating a session ID first with the your customer stripe ID as "customer" parameter and then pass the session ID to vue stripe checkout component. 

I got the subscription attached correctly to my logged in customer

**Comment by peterkracik** [comment] 2022-10-06 09:39
> @hcphoon01 You can solve this by generating a session ID first with the your customer stripe ID as "customer" parameter and then pass the session ID to vue stripe checkout component.
> 
> I got the subscription attached correctly to my logged in customer

@juloxrox could you please provide an example of how you create this session id?
